# Site settings
title: System-on-Chip Design & Verification
author:
  name: Choon Xiang Yeoh
  email: g00425056@atu.ie
description: "An FPGA VGA Driver Project Blog"

# Build settings
remote_theme: jekyll/minima
